"""add index on profiles.location_id

Revision ID: c1065f4511ad
Revises: e5cfca253956
Create Date: 2025-09-23 03:49:31.125693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1065f4511ad'
down_revision: Union[str, None] = 'e5cfca253956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profiles_location_id'), 'profiles', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_location_id'), table_name='profiles')
    # ### end Alembic commands ###
