"""initializing database schema for MVP

Revision ID: caab494b6d41
Revises:
Create Date: 2025-09-27 19:35:35.056063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'caab494b6d41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='ck_email_format'),
    sa.CheckConstraint("username ~ '^[a-zA-Z0-9_-]+$'", name='ck_username_format'),
    sa.CheckConstraint('length(password_hash) >= 60', name='ck_password_hash_length'),
    sa.CheckConstraint('length(username) >= 3', name='ck_username_min_length'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_updated_by'), 'users', ['updated_by'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_by'), 'organizations', ['created_by'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_updated_by'), 'organizations', ['updated_by'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.CheckConstraint('length(first_name) <= 100', name='ck_first_name_length'),
    sa.CheckConstraint('length(last_name) <= 100', name='ck_last_name_length'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_created_by'), 'profiles', ['created_by'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_updated_by'), 'profiles', ['updated_by'], unique=False)
    op.create_table('business_open_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_business_open_days_org')
    )
    op.create_index('idx_business_open_days_org_active', 'business_open_days', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_business_open_days_created_by'), 'business_open_days', ['created_by'], unique=False)
    op.create_index(op.f('ix_business_open_days_friday'), 'business_open_days', ['friday'], unique=False)
    op.create_index(op.f('ix_business_open_days_id'), 'business_open_days', ['id'], unique=False)
    op.create_index(op.f('ix_business_open_days_is_active'), 'business_open_days', ['is_active'], unique=False)
    op.create_index(op.f('ix_business_open_days_monday'), 'business_open_days', ['monday'], unique=False)
    op.create_index(op.f('ix_business_open_days_organization_id'), 'business_open_days', ['organization_id'], unique=False)
    op.create_index(op.f('ix_business_open_days_saturday'), 'business_open_days', ['saturday'], unique=False)
    op.create_index(op.f('ix_business_open_days_sunday'), 'business_open_days', ['sunday'], unique=False)
    op.create_index(op.f('ix_business_open_days_thursday'), 'business_open_days', ['thursday'], unique=False)
    op.create_index(op.f('ix_business_open_days_tuesday'), 'business_open_days', ['tuesday'], unique=False)
    op.create_index(op.f('ix_business_open_days_updated_by'), 'business_open_days', ['updated_by'], unique=False)
    op.create_index(op.f('ix_business_open_days_wednesday'), 'business_open_days', ['wednesday'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'staff', name='membershiprole'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_membership_user')
    )
    op.create_index('idx_membership_org', 'organization_members', ['organization_id'], unique=False)
    op.create_index('idx_membership_role', 'organization_members', ['role'], unique=False)
    op.create_index('idx_membership_user', 'organization_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_organization_members_created_by'), 'organization_members', ['created_by'], unique=False)
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_updated_by'), 'organization_members', ['updated_by'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('requirement_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_date', sa.Date(), nullable=False),
    sa.Column('requirement_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'requirement_date', name='uq_req_day_org_date')
    )
    op.create_index('idx_req_day_date', 'requirement_days', ['requirement_date'], unique=False)
    op.create_index('idx_req_day_org', 'requirement_days', ['organization_id'], unique=False)
    op.create_index(op.f('ix_requirement_days_created_by'), 'requirement_days', ['created_by'], unique=False)
    op.create_index(op.f('ix_requirement_days_id'), 'requirement_days', ['id'], unique=False)
    op.create_index(op.f('ix_requirement_days_organization_id'), 'requirement_days', ['organization_id'], unique=False)
    op.create_index(op.f('ix_requirement_days_requirement_date'), 'requirement_days', ['requirement_date'], unique=False)
    op.create_index(op.f('ix_requirement_days_requirement_day'), 'requirement_days', ['requirement_day'], unique=False)
    op.create_index(op.f('ix_requirement_days_updated_by'), 'requirement_days', ['updated_by'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Archived', name='rolestatus'), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', name='rolepriority'), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('salary_range_min', sa.Float(), nullable=True),
    sa.Column('salary_range_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='unique_role_name')
    )
    op.create_index('idx_role_org_name', 'roles', ['organization_id', 'name'], unique=False)
    op.create_index('idx_role_org_slug', 'roles', ['organization_id', 'slug'], unique=False)
    op.create_index('idx_role_priority', 'roles', ['priority'], unique=False)
    op.create_index('idx_role_status', 'roles', ['status'], unique=False)
    op.create_index(op.f('ix_roles_created_by'), 'roles', ['created_by'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_roles_priority'), 'roles', ['priority'], unique=False)
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=False)
    op.create_index(op.f('ix_roles_status'), 'roles', ['status'], unique=False)
    op.create_index(op.f('ix_roles_updated_by'), 'roles', ['updated_by'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Published', 'Archived', name='schedulestatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'week_start', name='unique_schedule_per_org_week')
    )
    op.create_index('idx_schedule_org_status', 'schedules', ['organization_id', 'status'], unique=False)
    op.create_index('idx_schedule_org_week_status', 'schedules', ['organization_id', 'week_start', 'status'], unique=False)
    op.create_index('idx_schedule_week_start', 'schedules', ['week_start'], unique=False)
    op.create_index(op.f('ix_schedules_created_by'), 'schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_organization_id'), 'schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_index(op.f('ix_schedules_updated_by'), 'schedules', ['updated_by'], unique=False)
    op.create_index(op.f('ix_schedules_week_start'), 'schedules', ['week_start'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='check_shift_time_order'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='unique_shift_name_per_org')
    )
    op.create_index('idx_shift_name', 'shifts', ['name'], unique=False)
    op.create_index('idx_shift_org', 'shifts', ['organization_id'], unique=False)
    op.create_index('idx_shift_org_start_end_time', 'shifts', ['organization_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_shifts_created_by'), 'shifts', ['created_by'], unique=False)
    op.create_index(op.f('ix_shifts_end_time'), 'shifts', ['end_time'], unique=False)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_name'), 'shifts', ['name'], unique=False)
    op.create_index(op.f('ix_shifts_organization_id'), 'shifts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shifts_start_time'), 'shifts', ['start_time'], unique=False)
    op.create_index(op.f('ix_shifts_updated_by'), 'shifts', ['updated_by'], unique=False)
    op.create_table('availability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('availability_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=True),
    sa.Column('availability_date', sa.Date(), nullable=True),
    sa.Column('availability_type', sa.Enum('Recurring', 'Exception', name='availabilitytype'), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Off', 'Unavailable', name='availabilitystatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'availability_date', 'availability_day', 'availability_type', 'shift_id', name='uq_avail_uniqueness')
    )
    op.create_index(op.f('ix_availability_availability_date'), 'availability', ['availability_date'], unique=False)
    op.create_index(op.f('ix_availability_availability_day'), 'availability', ['availability_day'], unique=False)
    op.create_index(op.f('ix_availability_availability_type'), 'availability', ['availability_type'], unique=False)
    op.create_index(op.f('ix_availability_created_by'), 'availability', ['created_by'], unique=False)
    op.create_index(op.f('ix_availability_id'), 'availability', ['id'], unique=False)
    op.create_index(op.f('ix_availability_organization_id'), 'availability', ['organization_id'], unique=False)
    op.create_index(op.f('ix_availability_shift_id'), 'availability', ['shift_id'], unique=False)
    op.create_index(op.f('ix_availability_status'), 'availability', ['status'], unique=False)
    op.create_index(op.f('ix_availability_updated_by'), 'availability', ['updated_by'], unique=False)
    op.create_index(op.f('ix_availability_user_id'), 'availability', ['user_id'], unique=False)
    op.create_table('membership_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('Invite', 'Request', name='membershiprequesttype'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Rejected', 'Cancelled', name='membershiprequeststatus'), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'manager', 'staff', name='membershiprole'), nullable=True),
    sa.Column('primary_role_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['primary_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'status', name='uq_active_membership_request')
    )
    op.create_index('idx_membership_request_org', 'membership_requests', ['organization_id'], unique=False)
    op.create_index('idx_membership_request_user', 'membership_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_membership_requests_created_by'), 'membership_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_membership_requests_id'), 'membership_requests', ['id'], unique=False)
    op.create_index(op.f('ix_membership_requests_invited_by_user_id'), 'membership_requests', ['invited_by_user_id'], unique=False)
    op.create_index(op.f('ix_membership_requests_organization_id'), 'membership_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_membership_requests_status'), 'membership_requests', ['status'], unique=False)
    op.create_index(op.f('ix_membership_requests_type'), 'membership_requests', ['type'], unique=False)
    op.create_index(op.f('ix_membership_requests_updated_by'), 'membership_requests', ['updated_by'], unique=False)
    op.create_index(op.f('ix_membership_requests_user_id'), 'membership_requests', ['user_id'], unique=False)
    op.create_table('membership_role_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'role_id', name='uq_membership_role')
    )
    op.create_index('idx_membership_role_assign_primary', 'membership_role_assignments', ['membership_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_membership_role_assignments_created_by'), 'membership_role_assignments', ['created_by'], unique=False)
    op.create_index(op.f('ix_membership_role_assignments_id'), 'membership_role_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_membership_role_assignments_is_primary'), 'membership_role_assignments', ['is_primary'], unique=False)
    op.create_index(op.f('ix_membership_role_assignments_membership_id'), 'membership_role_assignments', ['membership_id'], unique=False)
    op.create_index(op.f('ix_membership_role_assignments_role_id'), 'membership_role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_membership_role_assignments_updated_by'), 'membership_role_assignments', ['updated_by'], unique=False)
    op.create_table('requirement_day_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('requirement_day_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requirement_day_id'], ['requirement_days.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_day_id', 'role_id', 'shift_id', name='uq_req_day_item_unique')
    )
    op.create_index('idx_req_day_item_org', 'requirement_day_items', ['organization_id'], unique=False)
    op.create_index('idx_req_day_item_role', 'requirement_day_items', ['role_id'], unique=False)
    op.create_index('idx_req_day_item_shift', 'requirement_day_items', ['shift_id'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_created_by'), 'requirement_day_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_id'), 'requirement_day_items', ['id'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_organization_id'), 'requirement_day_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_required_count'), 'requirement_day_items', ['required_count'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_requirement_day_id'), 'requirement_day_items', ['requirement_day_id'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_role_id'), 'requirement_day_items', ['role_id'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_shift_id'), 'requirement_day_items', ['shift_id'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_updated_by'), 'requirement_day_items', ['updated_by'], unique=False)
    op.create_index(op.f('ix_requirement_day_items_weekday'), 'requirement_day_items', ['weekday'], unique=False)
    op.create_table('schedule_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'schedule_date', name='uq_day_schedule_date')
    )
    op.create_index('idx_schedule_day_date', 'schedule_days', ['schedule_date'], unique=False)
    op.create_index('idx_schedule_day_org_date', 'schedule_days', ['organization_id', 'schedule_date'], unique=False)
    op.create_index('idx_schedule_day_schedule', 'schedule_days', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_days_created_by'), 'schedule_days', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedule_days_id'), 'schedule_days', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_days_organization_id'), 'schedule_days', ['organization_id'], unique=False)
    op.create_index(op.f('ix_schedule_days_schedule_date'), 'schedule_days', ['schedule_date'], unique=False)
    op.create_index(op.f('ix_schedule_days_schedule_id'), 'schedule_days', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_days_updated_by'), 'schedule_days', ['updated_by'], unique=False)
    op.create_table('time_off_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('start_dt', sa.DateTime(), nullable=False),
    sa.Column('end_dt', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='requeststatus'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_requests_approved_at'), 'time_off_requests', ['approved_at'], unique=False)
    op.create_index(op.f('ix_time_off_requests_approver_id'), 'time_off_requests', ['approver_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_created_by'), 'time_off_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_time_off_requests_end_dt'), 'time_off_requests', ['end_dt'], unique=False)
    op.create_index(op.f('ix_time_off_requests_id'), 'time_off_requests', ['id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_organization_id'), 'time_off_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_shift_id'), 'time_off_requests', ['shift_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_start_dt'), 'time_off_requests', ['start_dt'], unique=False)
    op.create_index(op.f('ix_time_off_requests_status'), 'time_off_requests', ['status'], unique=False)
    op.create_index(op.f('ix_time_off_requests_updated_by'), 'time_off_requests', ['updated_by'], unique=False)
    op.create_index(op.f('ix_time_off_requests_user_id'), 'time_off_requests', ['user_id'], unique=False)
    op.create_table('role_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_day_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['schedule_day_id'], ['schedule_days.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'schedule_day_id', name='uq_roleslot_role_day')
    )
    op.create_index('idx_roleslot_org_role', 'role_slots', ['organization_id', 'role_id'], unique=False)
    op.create_index('idx_roleslot_required_count', 'role_slots', ['required_count'], unique=False)
    op.create_index('idx_roleslot_schedule_day', 'role_slots', ['schedule_day_id'], unique=False)
    op.create_index(op.f('ix_role_slots_created_by'), 'role_slots', ['created_by'], unique=False)
    op.create_index(op.f('ix_role_slots_id'), 'role_slots', ['id'], unique=False)
    op.create_index(op.f('ix_role_slots_organization_id'), 'role_slots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_role_slots_role_id'), 'role_slots', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_slots_schedule_day_id'), 'role_slots', ['schedule_day_id'], unique=False)
    op.create_index(op.f('ix_role_slots_shift_id'), 'role_slots', ['shift_id'], unique=False)
    op.create_index(op.f('ix_role_slots_updated_by'), 'role_slots', ['updated_by'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_slot_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Confirmed', 'InProgress', 'Completed', 'Cancelled', 'NoShow', name='assignmentstatus'), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', name='assignmentpriority'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_slot_id'], ['role_slots.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_slot_id', 'user_id', name='uq_assignment_slot_user')
    )
    op.create_index('idx_assignment_role_slot', 'assignments', ['role_slot_id'], unique=False)
    op.create_index('idx_assignment_user_status', 'assignments', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_assignments_approved_by'), 'assignments', ['approved_by'], unique=False)
    op.create_index(op.f('ix_assignments_assigned_at'), 'assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_assignments_assigned_by'), 'assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_assignments_confirmed_at'), 'assignments', ['confirmed_at'], unique=False)
    op.create_index(op.f('ix_assignments_created_by'), 'assignments', ['created_by'], unique=False)
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_index(op.f('ix_assignments_organization_id'), 'assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assignments_priority'), 'assignments', ['priority'], unique=False)
    op.create_index(op.f('ix_assignments_role_slot_id'), 'assignments', ['role_slot_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_updated_by'), 'assignments', ['updated_by'], unique=False)
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_updated_by'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_role_slot_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_priority'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_organization_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_created_by'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_confirmed_at'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_by'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_at'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_approved_by'), table_name='assignments')
    op.drop_index('idx_assignment_user_status', table_name='assignments')
    op.drop_index('idx_assignment_role_slot', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_role_slots_updated_by'), table_name='role_slots')
    op.drop_index(op.f('ix_role_slots_shift_id'), table_name='role_slots')
    op.drop_index(op.f('ix_role_slots_schedule_day_id'), table_name='role_slots')
    op.drop_index(op.f('ix_role_slots_role_id'), table_name='role_slots')
    op.drop_index(op.f('ix_role_slots_organization_id'), table_name='role_slots')
    op.drop_index(op.f('ix_role_slots_id'), table_name='role_slots')
    op.drop_index(op.f('ix_role_slots_created_by'), table_name='role_slots')
    op.drop_index('idx_roleslot_schedule_day', table_name='role_slots')
    op.drop_index('idx_roleslot_required_count', table_name='role_slots')
    op.drop_index('idx_roleslot_org_role', table_name='role_slots')
    op.drop_table('role_slots')
    op.drop_index(op.f('ix_time_off_requests_user_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_updated_by'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_status'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_start_dt'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_shift_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_organization_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_end_dt'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_created_by'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_approver_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_approved_at'), table_name='time_off_requests')
    op.drop_table('time_off_requests')
    op.drop_index(op.f('ix_schedule_days_updated_by'), table_name='schedule_days')
    op.drop_index(op.f('ix_schedule_days_schedule_id'), table_name='schedule_days')
    op.drop_index(op.f('ix_schedule_days_schedule_date'), table_name='schedule_days')
    op.drop_index(op.f('ix_schedule_days_organization_id'), table_name='schedule_days')
    op.drop_index(op.f('ix_schedule_days_id'), table_name='schedule_days')
    op.drop_index(op.f('ix_schedule_days_created_by'), table_name='schedule_days')
    op.drop_index('idx_schedule_day_schedule', table_name='schedule_days')
    op.drop_index('idx_schedule_day_org_date', table_name='schedule_days')
    op.drop_index('idx_schedule_day_date', table_name='schedule_days')
    op.drop_table('schedule_days')
    op.drop_index(op.f('ix_requirement_day_items_weekday'), table_name='requirement_day_items')
    op.drop_index(op.f('ix_requirement_day_items_updated_by'), table_name='requirement_day_items')
    op.drop_index(op.f('ix_requirement_day_items_shift_id'), table_name='requirement_day_items')
    op.drop_index(op.f('ix_requirement_day_items_role_id'), table_name='requirement_day_items')
    op.drop_index(op.f('ix_requirement_day_items_requirement_day_id'), table_name='requirement_day_items')
    op.drop_index(op.f('ix_requirement_day_items_required_count'), table_name='requirement_day_items')
    op.drop_index(op.f('ix_requirement_day_items_organization_id'), table_name='requirement_day_items')
    op.drop_index(op.f('ix_requirement_day_items_id'), table_name='requirement_day_items')
    op.drop_index(op.f('ix_requirement_day_items_created_by'), table_name='requirement_day_items')
    op.drop_index('idx_req_day_item_shift', table_name='requirement_day_items')
    op.drop_index('idx_req_day_item_role', table_name='requirement_day_items')
    op.drop_index('idx_req_day_item_org', table_name='requirement_day_items')
    op.drop_table('requirement_day_items')
    op.drop_index(op.f('ix_membership_role_assignments_updated_by'), table_name='membership_role_assignments')
    op.drop_index(op.f('ix_membership_role_assignments_role_id'), table_name='membership_role_assignments')
    op.drop_index(op.f('ix_membership_role_assignments_membership_id'), table_name='membership_role_assignments')
    op.drop_index(op.f('ix_membership_role_assignments_is_primary'), table_name='membership_role_assignments')
    op.drop_index(op.f('ix_membership_role_assignments_id'), table_name='membership_role_assignments')
    op.drop_index(op.f('ix_membership_role_assignments_created_by'), table_name='membership_role_assignments')
    op.drop_index('idx_membership_role_assign_primary', table_name='membership_role_assignments')
    op.drop_table('membership_role_assignments')
    op.drop_index(op.f('ix_membership_requests_user_id'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_updated_by'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_type'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_status'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_organization_id'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_invited_by_user_id'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_id'), table_name='membership_requests')
    op.drop_index(op.f('ix_membership_requests_created_by'), table_name='membership_requests')
    op.drop_index('idx_membership_request_user', table_name='membership_requests')
    op.drop_index('idx_membership_request_org', table_name='membership_requests')
    op.drop_table('membership_requests')
    op.drop_index(op.f('ix_availability_user_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_updated_by'), table_name='availability')
    op.drop_index(op.f('ix_availability_status'), table_name='availability')
    op.drop_index(op.f('ix_availability_shift_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_organization_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_created_by'), table_name='availability')
    op.drop_index(op.f('ix_availability_availability_type'), table_name='availability')
    op.drop_index(op.f('ix_availability_availability_day'), table_name='availability')
    op.drop_index(op.f('ix_availability_availability_date'), table_name='availability')
    op.drop_table('availability')
    op.drop_index(op.f('ix_shifts_updated_by'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_start_time'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_organization_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_name'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_end_time'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_created_by'), table_name='shifts')
    op.drop_index('idx_shift_org_start_end_time', table_name='shifts')
    op.drop_index('idx_shift_org', table_name='shifts')
    op.drop_index('idx_shift_name', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_schedules_week_start'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_updated_by'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_organization_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_created_by'), table_name='schedules')
    op.drop_index('idx_schedule_week_start', table_name='schedules')
    op.drop_index('idx_schedule_org_week_status', table_name='schedules')
    op.drop_index('idx_schedule_org_status', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_roles_updated_by'), table_name='roles')
    op.drop_index(op.f('ix_roles_status'), table_name='roles')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_index(op.f('ix_roles_priority'), table_name='roles')
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_by'), table_name='roles')
    op.drop_index('idx_role_status', table_name='roles')
    op.drop_index('idx_role_priority', table_name='roles')
    op.drop_index('idx_role_org_slug', table_name='roles')
    op.drop_index('idx_role_org_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_requirement_days_updated_by'), table_name='requirement_days')
    op.drop_index(op.f('ix_requirement_days_requirement_day'), table_name='requirement_days')
    op.drop_index(op.f('ix_requirement_days_requirement_date'), table_name='requirement_days')
    op.drop_index(op.f('ix_requirement_days_organization_id'), table_name='requirement_days')
    op.drop_index(op.f('ix_requirement_days_id'), table_name='requirement_days')
    op.drop_index(op.f('ix_requirement_days_created_by'), table_name='requirement_days')
    op.drop_index('idx_req_day_org', table_name='requirement_days')
    op.drop_index('idx_req_day_date', table_name='requirement_days')
    op.drop_table('requirement_days')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_updated_by'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_created_by'), table_name='organization_members')
    op.drop_index('idx_membership_user', table_name='organization_members')
    op.drop_index('idx_membership_role', table_name='organization_members')
    op.drop_index('idx_membership_org', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_business_open_days_wednesday'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_updated_by'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_tuesday'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_thursday'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_sunday'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_saturday'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_organization_id'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_monday'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_is_active'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_id'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_friday'), table_name='business_open_days')
    op.drop_index(op.f('ix_business_open_days_created_by'), table_name='business_open_days')
    op.drop_index('idx_business_open_days_org_active', table_name='business_open_days')
    op.drop_table('business_open_days')
    op.drop_index(op.f('ix_profiles_updated_by'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_created_by'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_organizations_updated_by'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_by'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_by'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
